# Utility

- name: Install system utility
  apt: pkg={{ item }}
  with_items:
    # - python-minimal
    - python-zipstream
    - aptitude
    - htop
    - git-core
    - build-essential
    - sshguard
    - vnstat
    - dstat

- apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 31536000
