---

- name: provisining for cheapcdn

  vars_files:
    - vars/secret.yml
    - vars/main.yml

  sudo: yes
  hosts: production

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

  roles:
    # - { role: custom/common }
    # - { role: custom/swapfile }
    # - { role: custom/adduser }
    # - { role: galaxy/geerlingguy.nginx }
    # - { role: galaxy/ansible-minio }
    # - { role: galaxy/joshualund.golang }
    - { role: custom/cheapcdn }
