---

- name: provisining for cheapcdn

  vars_files:
    - vars/secret.yml
    - vars/main.yml

  sudo: yes
  hosts: production
  # hosts: logger
  # hosts: vagrant

  # strategy: free

  roles:
    - { role: custom/common }
    - { role: custom/swapfile }
    - { role: custom/adduser }
    - { role: custom/sysctl }
    - { role: custom/minio }
    - { role: custom/python }
    - { role: custom/logger }                 # Send rsyslog

    - { role: custom/prepare }                # Prepared for all of below

    - { role: galaxy/ansible-minio }
    - { role: galaxy/joshualund.golang }
    - { role: galaxy/zzet.rbenv }

    - { role: custom/elao.supervisor.custom } # Configure einhorn into superbisor
    - { role: custom/scraper }                # Install scraper
    - { role: custom/cheapcdn }               # Install cheapcdn with golang
    - { role: custom/einhorn }                # Install einhorn with rbenv@ruby
    - { role: galaxy/geerlingguy.nginx }      # Configure cheapcdn into nginx
    - { role: custom/nginx }                  # Build with slice_module
    - { role: custom/monit }                  # Configure monit
    - { role: custom/monitor }                # Configure external monitor
    - { role: custom/restart }                # Graceful restart einhorn
