---

- name: provisining for cheapcdn

  vars_files:
    - vars/secret.yml
    - vars/main.yml

  sudo: yes
  hosts: production
  # hosts: vagrant

  strategy: free

  #gather_facts: False
  #pre_tasks:
  #  - name: Install python for Ansible
  #    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  #    changed_when: False
  #  - setup: # aka gather_facts

  roles:
    - { role: custom/common }
    - { role: custom/swapfile }
    - { role: custom/adduser }
    - { role: custom/minio }

    - { role: galaxy/ansible-minio }
    - { role: galaxy/joshualund.golang }
    - { role: galaxy/zzet.rbenv }

    - { role: custom/cheapcdn }               # Install cheapcdn with golang
    - { role: custom/einhorn }                # Install einhorn with rbenv@ruby
    - { role: custom/elao.supervisor.custom } # Configure einhorn into superbisor
    - { role: galaxy/geerlingguy.nginx }      # Configure cheapcdn into nginx
    - { role: custom/restart }                # Configure cheapcdn into nginx
