---

- name: Restart minio and graceful restart cheapcdn

  vars_files:
    - vars/secret.yml
    - vars/main.yml

  sudo: yes
  hosts: production
  # hosts: vagrant

  strategy: free

  tasks:
    - name: restart supervisor
      command: /bin/systemctl restart supervisor
