---

- name: Restart minio and graceful restart cheapcdn

  vars_files:
    - vars/secret.yml
    - vars/main.yml

  sudo: yes
  hosts: vagrant
  # hosts: production

  strategy: free

  roles:
    - { role: custom/restart }                # Configure cheapcdn into nginx

  tasks:
    - name: Install NTP
      apt: pkg={{ item }}
      with_items:
        - ntp

    - name: update date
      shell: /etc/init.d/ntp restart

    - name: kill minio
      shell: pkill minio
      ignore_errors: yes

    - name: stop minio
      shell: systemctl stop minio
    - name: stop minio
      shell: systemctl stop minio
    - name: stop minio
      shell: systemctl stop minio

    - name: start minio
      shell: systemctl start minio
    - name: start minio
      shell: systemctl start minio

    # - name: restart minio
      # shell: systemctl restart minio
