---

- name: config > Template
  template:
    src:  "{{ elao_supervisor_config_template|ternary(elao_supervisor_config_template, 'config/base.conf.j2') }}"
    dest: "{{ elao_supervisor_config_file }}"
  when: (elao_supervisor_config_template is not none) or (elao_supervisor_config|length)
  notify:
    - supervisor restart
