- name: Added Python 3.6 ppa
  apt_repository:
    repo: 'ppa:jonathonf/python-3.6'

- name: Install Python
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python3.6
    - python3.6-dev
    - python3.6-venv

- name: make venv
  shell: cd /home/{{ username }} && /usr/bin/python3.6 -m venv venv
  sudo_user: "{{ username }}"
  ignore_errors: True
