- name: Install ntp
  apt: pkg={{ item }}
  with_items:
    - ntp  # workaround: https://github.com/minio/minio/issues/3446#issuecomment-267011376

- name: Change permission mino directory
  file:
    path: /mnt
    mode: 0775
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: remove old files on cron
  cron:
    name: remove old files on cron
    minute: "*/20"
    job: "/usr/bin/find /mnt/{{ inventory_hostname }}/openshare -maxdepth 1 -type f -user {{ username }} -mtime +10 -exec rm {} \\;"
