- name: Check swap file type
  command: file {{ swap_file_path }}
  register: swapfile
  ignore_errors: yes

- name: Create swap file
  command: fallocate -l {{ swap_file_size_gb }}G {{ swap_file_path }}
  when: swapfile.stdout.find('swap file') == -1

- name: Change swap file permissions
  file: path={{ swap_file_path }}
        owner=root
        group=root
        mode=0600
  when: swapfile.stdout.find('swap file') == -1

- name: Make swap file
  command: "sudo mkswap {{ swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
