- name: Install relevent module form apt
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libgd2-xpm-dev
    - libgeoip-dev
    - libxslt-dev
    - build-essential

- name: go get nginx-build
  shell: /usr/local/go/bin/go get -u github.com/cubicdaiya/nginx-build

- stat:
    path: /root/work/nginx/1.11.12/nginx-1.11.12
  register: has_nginx

- name: Build nginx with mainly slice module
  shell: /root/go/bin/nginx-build -d /root/work -v 1.11.12 -zlib -pcre -openssl
            --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf
            --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid
            --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi
            --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi
            --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module
            --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module
            --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module
            --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module
            --with-mail --with-mail_ssl_module --with-threads --with-http_slice_module --with-http_mp4_module --with-http_flv_module
  when: has_nginx.stat.exists == False
  notify: restart nginx

- name: Make install nginx into /usr/share
  shell: cd /root/work/nginx/1.11.12/nginx-1.11.12 &&
         make install &&
         rm -f /usr/sbin/nginx && ln -fs /usr/share/nginx/sbin/nginx /usr/sbin/nginx
  when: has_nginx.stat.exists == False
  notify: restart nginx
