---

dependencies: []

galaxy_info:

  author:              Elao
  company:             Elao
  description: >
    Supervisor role
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: Debian
      versions:
        - wheezy
  categories:
    - development
    - web
